Repository lightningd/plugins, pull requests merged in 2019-05, with the labels that each got.

#19 probe: Actually add a sensible return value to the probe method
  probe/probe.py
Labels: ready for review

#23 fix: a race condition in the summary plugin
  summary/summary.py
Labels: bugfix, ready for review

#25 feat: summary adds descriptive table header
  summary/summary.py
Labels: enhancement, ready for review

#24 fix: rebalance channel selection
  rebalance/rebalance.py
Labels: bugfix, ready for review

#30 rebalance: fix issue 29
  rebalance/rebalance.py
Labels: bugfix, ready for review

#33 Cleanup rebalance sendinvoiceless
  rebalance/README.md
  rebalance/rebalance.py
  sendinvoiceless/README.md
  sendinvoiceless/sendinvoiceless.py
  summary/README.md
  summary/summary.py
Labels: cleanup, ready for review
